### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/observable#107]
It seems the master branch is already upgrade to null safety.  Is it ready to publish on pub?

**Comment by markegli** [comment]
Sorry for the slow response on this, Jonathan! I'm on paternity leave so haven't been keeping up with messages.

I was hoping to fix #91 before publishing to pub, but I can put that in a separate version if this is urgent for you. I see you've worked around the issue for the time being, but let me know if you'd like me to publish to pub now so you can switch back to the observable pub package sooner rather than later.

**Comment by jodinathan** [comment]
congrats! 🥳
Wish everything to be safe and well.   

We ended up fixing the issues in the tests and creating another package: http://pub.dev/packages/change_notifier  
Which also has the `ChangeNotifier` from Flutter Foundation.

**Comment by markegli** [comment]
Observable 0.24.0 with the null safety migration has been published.
