### ISSUE TITLE
ObservableList doesn't implement all ListBase methods

### ISSUE THREAD

**Issue by peterjosling** [dart-lang/observable#86]
Calling `clear()` on an ObservableList removes all items, but doesn't notify any observers. Same for `removeLast()`, and presumably other methods as well.

**Comment by markegli** [comment]
Peter, do you have any example code showing these not working?

Since ListBase implements all its mutations in terms of `operator[]=` and `length=` and ObservableList overrides both of these, all List methods should notify correctly. Additionally, there are test cases in observable_list_test.dart for `clear()` and `removeLast()` that currently pass.

**Comment by ncroll** [comment]
We believe that this is working, but please reopen if you have an example where it's not.
